# Devise/OAuth credentials:
#
oauth:
  google_oauth2:
    client_id: aaaa.apps.googleusercontent.com
    client_secret: aaa-bbbb-cccc-dddd
  github:
    client_id: aaa.bbbbb
    client_secret: aaaa

# Pay credentials for Stripe/Paddle (Payments gem):
#
stripe:
  private_key: sk_test_aaaa
  public_key: pk_test_aaaa
  signing_secret:
    - whsec_aaaa
paddle_billing:
  client_token: test_aaaa
  api_key: aaaa
  signing_secret: pdl_ntfset_aaaa/bbbb
  environment: sandbox
